namespace ChatAppWSServer.Models
{
    public enum Opcode
    {
        LOGIN_SUCCESS,
        LOGIN_FAIL,
        REGISTER_SUCCESS,
        REGISTER_FAIL,
        CREATEDIRECTMESSAGE_SUCCESS,
        CREATEDIRECTMESSAGE_FAIL,
        ADDFRIEND_SUCCESS,
        ADDFRIEND_FAIL,
        GETFRIENDS_SUCCESS,
        GETFRIENDS_FAIL,
        GETFRIEND_SUCCESS,
        GETFRIEND_FAIL,
        GETDIRECTMESSAGES_SUCCESS,
        GETDIRECTMESSAGES_FAIL
    }
}